### ISSUE TITLE
Separating the information in lyrics line in Symbtr

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#4]
In the SymbTr files, the section information exists. This information is structured differently for instrumental and vocal compositions:
- [x] #5: Copy the structure information in instrumental compositions 
- [x] #6: Exporting the information in lyrics line in SymbTr
- [x] #10: Copy the bridge information in compositions
- [x] Rarely the usul changes are indicated in the lyrics. The should be used to change the rhythmic structure according MusicXML schema.

**Comment by burakuyar** [comment]
Check #5
